"""渲染本地 Nginx S3 图片代理配置。

该脚本只在启动或刷新代理时读取 S3 清单，并把每张图片的本地短 URL
映射到真实 S3 HTTPS URL 或预签名 URL。图片请求的热路径完全由 Nginx
处理，避免 Python 代理在 Label Studio 批量加载图片时成为瓶颈。
"""

# pylint: disable=line-too-long,import-error,too-many-arguments,too-many-locals,too-many-positional-arguments

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from scripts.s3.brand_s3_config import (  # pylint: disable=wrong-import-position
    DEFAULT_CONFIG_PATH,
    BrandS3Config,
    https_url_for_object,
    load_config,
    load_manifest_records,
    nginx_url_for_object,
)
from scripts.s3.upload_images_to_s3 import build_s3_client  # pylint: disable=wrong-import-position


@dataclass(frozen=True)
class NginxRoute:
    """一条 Nginx 本地图片路径到上游 S3 URL 的映射。"""

    local_path: str
    upstream_url: str
    s3_key: str


def positive_int(value: str) -> int:
    """解析正整数参数。"""
    parsed = int(value)
    if parsed <= 0:
        raise argparse.ArgumentTypeError("必须是正整数")
    return parsed


def nginx_quote(value: str) -> str:
    """把字符串转为 Nginx 配置中的双引号安全字面量。"""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def local_path_for_key(proxy_base_url: str, dataset_name: str, key: str) -> str:
    """根据公共 URL helper 计算 Nginx map 中使用的本地 URI 路径。"""
    local_url = nginx_url_for_object(proxy_base_url, dataset_name, key)
    return urlsplit(local_url).path


def upstream_url_for_record(record: dict[str, Any], config: BrandS3Config) -> str:
    """读取或补齐一条清单记录对应的公开 S3 HTTPS URL。"""
    bucket = str(record.get("s3_bucket") or config.bucket)
    key = str(record.get("s3_key") or "")
    region = str(record.get("region") or config.region)
    if not bucket or not key:
        raise ValueError(f"S3 清单记录缺少 s3_bucket 或 s3_key：{record}")
    return str(record.get("https_url") or https_url_for_object(bucket, key, region, config.public_base_url))


def presigned_url_for_record(record: dict[str, Any], config: BrandS3Config, s3_client: Any, expires: int) -> str:
    """为私有桶对象生成 Nginx 可直接回源的短期预签名 URL。"""
    bucket = str(record.get("s3_bucket") or config.bucket)
    key = str(record.get("s3_key") or "")
    if not bucket or not key:
        raise ValueError(f"S3 清单记录缺少 s3_bucket 或 s3_key：{record}")
    return str(
        s3_client.generate_presigned_url(
            "get_object",
            Params={"Bucket": bucket, "Key": key},
            ExpiresIn=expires,
        )
    )


def build_routes(records: list[dict[str, Any]], config: BrandS3Config, mode: str, expires: int) -> list[NginxRoute]:
    """把 S3 清单转换为 Nginx map 路由列表。"""
    routes_by_path: dict[str, NginxRoute] = {}
    s3_client = build_s3_client(config) if mode == "presign" else None
    for index, record in enumerate(records, start=1):
        key = str(record.get("s3_key") or "")
        if not key:
            raise ValueError(f"第 {index} 条 S3 清单缺少 s3_key：{record}")
        dataset_name = str(record.get("dataset_name") or config.dataset_name)
        local_path = local_path_for_key(config.proxy_base_url, dataset_name, key)
        upstream_url = (
            presigned_url_for_record(record, config, s3_client, expires)
            if mode == "presign"
            else upstream_url_for_record(record, config)
        )
        routes_by_path[local_path] = NginxRoute(local_path=local_path, upstream_url=upstream_url, s3_key=key)
    return [routes_by_path[path] for path in sorted(routes_by_path)]


def render_map(routes: list[NginxRoute]) -> str:
    """渲染 Nginx `map` 配置，把本地 URI 解析为上游 S3 URL。"""
    lines = [
        "# Generated by scripts/s3/render_nginx_image_proxy.py; do not edit by hand.",
        "map $uri $s3_image_upstream {",
        "    default \"\";",
    ]
    for route in routes:
        lines.append(f"    {nginx_quote(route.local_path)} {nginx_quote(route.upstream_url)};")
    lines.append("}")
    return "\n".join(lines) + "\n"


def render_config(
    host: str,
    port: int,
    allowed_origin: str,
    map_path: Path,
    cache_dir: Path,
    pid_path: Path,
    log_dir: Path,
) -> str:
    """渲染完整 Nginx 配置文件。"""
    return f"""# Generated by scripts/s3/render_nginx_image_proxy.py; do not edit by hand.
pid {nginx_quote(str(pid_path))};
worker_processes auto;

events {{
    worker_connections 1024;
}}

http {{
    include {nginx_quote(str(map_path))};
    access_log {nginx_quote(str(log_dir / "access.log"))};
    error_log {nginx_quote(str(log_dir / "error.log"))};
    proxy_cache_path {nginx_quote(str(cache_dir))} levels=1:2 keys_zone=s3_image_cache:128m max_size=20g inactive=7d use_temp_path=off;
    resolver 1.1.1.1 8.8.8.8 valid=300s ipv6=off;

    server {{
        listen {host}:{port};
        server_name localhost;

        add_header Access-Control-Allow-Origin {nginx_quote(allowed_origin)} always;
        add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
        add_header Access-Control-Allow-Headers "Content-Type" always;
        add_header X-Cache-Status $upstream_cache_status always;

        location = /healthz {{
            default_type text/plain;
            return 200 "ok\\n";
        }}

        location /image/ {{
            if ($request_method = OPTIONS) {{
                return 204;
            }}
            if ($s3_image_upstream = "") {{
                return 404;
            }}

            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host $proxy_host;
            proxy_ssl_server_name on;
            proxy_ssl_name $proxy_host;
            proxy_buffering on;
            proxy_cache s3_image_cache;
            proxy_cache_key $uri;
            proxy_cache_lock on;
            proxy_cache_valid 200 302 7d;
            proxy_cache_valid 404 10m;
            proxy_cache_use_stale error timeout invalid_header updating http_500 http_502 http_503 http_504;
            proxy_ignore_headers Set-Cookie;
            proxy_pass $s3_image_upstream;
        }}
    }}
}}
"""


def write_nginx_files(
    records: list[dict[str, Any]],
    config: BrandS3Config,
    mode: str,
    expires: int,
    host: str,
    port: int,
    output_conf: Path,
    map_output: Path,
    cache_dir: Path,
    pid_path: Path,
) -> list[NginxRoute]:
    """生成 Nginx 配置、map 文件和运行目录。"""
    routes = build_routes(records, config, mode, expires)
    if not routes:
        raise ValueError("S3 清单为空，无法生成 Nginx 图片代理配置。")
    output_conf.parent.mkdir(parents=True, exist_ok=True)
    map_output.parent.mkdir(parents=True, exist_ok=True)
    cache_dir.mkdir(parents=True, exist_ok=True)
    pid_path.parent.mkdir(parents=True, exist_ok=True)
    log_dir = output_conf.parent / "logs"
    log_dir.mkdir(parents=True, exist_ok=True)
    map_output.write_text(render_map(routes), encoding="utf-8")
    output_conf.write_text(
        render_config(host, port, config.proxy_allowed_origin, map_output, cache_dir, pid_path, log_dir),
        encoding="utf-8",
    )
    return routes


def parse_args() -> argparse.Namespace:
    """解析命令行参数。"""
    parser = argparse.ArgumentParser(description="生成本地 Nginx S3 图片代理配置。")
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG_PATH, help="S3 工作流 YAML 配置路径")
    parser.add_argument("--manifest", type=Path, default=None, help="S3 图片清单 JSON")
    parser.add_argument("--dataset-name", default="", help="数据集短名称")
    parser.add_argument("--dataset-root", default="", help="本地 S3 工作流输出根目录")
    parser.add_argument("--bucket", default="", help="S3 桶名")
    parser.add_argument("--region", default="", help="S3 区域")
    parser.add_argument("--profile", default="", help="本机 AWS profile")
    parser.add_argument("--endpoint-url", default="", help="兼容 S3 服务 endpoint URL")
    parser.add_argument("--public-base-url", default="", help="自定义公开访问 base URL")
    parser.add_argument("--proxy-base-url", default="", help="本地 Nginx 图片代理 base URL")
    parser.add_argument("--allowed-origin", default="", help="允许访问图片的 Label Studio origin")
    parser.add_argument("--host", default="127.0.0.1", help="Nginx 监听地址")
    parser.add_argument("--port", type=positive_int, default=3010, help="Nginx 监听端口")
    parser.add_argument("--mode", choices=["direct", "presign"], default="presign", help="Nginx 回源模式：direct 用公开 HTTPS，presign 用预签名 URL")
    parser.add_argument("--presign-expires", type=positive_int, default=604800, help="预签名 URL 有效秒数，默认 7 天")
    parser.add_argument("--output-conf", type=Path, required=True, help="输出 Nginx 主配置路径")
    parser.add_argument("--map-output", type=Path, required=True, help="输出 Nginx map 配置路径")
    parser.add_argument("--cache-dir", type=Path, required=True, help="Nginx 图片缓存目录")
    parser.add_argument("--pid-path", type=Path, required=True, help="Nginx pid 文件路径")
    return parser.parse_args()


def main() -> None:
    """脚本入口：读取清单并写出 Nginx 配置。"""
    args = parse_args()
    config = load_config(
        args.config,
        dataset_name=args.dataset_name,
        dataset_root=args.dataset_root,
        bucket=args.bucket,
        region=args.region,
        profile=args.profile,
        endpoint_url=args.endpoint_url,
        public_base_url=args.public_base_url,
        proxy_base_url=args.proxy_base_url,
        proxy_allowed_origin=args.allowed_origin,
    )
    manifest_path = args.manifest or config.manifest_json
    records = load_manifest_records(manifest_path)
    routes = write_nginx_files(
        records,
        config,
        args.mode,
        args.presign_expires,
        args.host,
        args.port,
        args.output_conf.expanduser().resolve(),
        args.map_output.expanduser().resolve(),
        args.cache_dir.expanduser().resolve(),
        args.pid_path.expanduser().resolve(),
    )
    print(f"Nginx 图片代理配置：{args.output_conf}")
    print(f"Nginx 图片代理映射：{args.map_output}")
    print(f"routes={len(routes)}, mode={args.mode}, proxy_base_url={config.proxy_base_url}")
    if args.mode == "presign":
        print(f"presign_expires={args.presign_expires} 秒，到期前请重新执行 reload/start 刷新映射。")


if __name__ == "__main__":
    main()
